# Generated by Django 5.1.1 on 2024-10-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/', verbose_name='profile picture'),
        ),
    ]
