# Generated by Django 5.1.1 on 2024-10-11 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_address_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
