# Generated by Django 5.1 on 2024-09-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cpuproduct_alter_category_description_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
    ]
