# Generated by Django 5.1 on 2024-09-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
