# Generated by Django 5.1 on 2024-09-22 15:17

import product.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_review_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPUProduct",
            fields=[],
            options={
                "verbose_name": "GPU product",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(product.models.ProductMixin, "product.product"),
        ),
    ]
